### ISSUE TITLE
Get Blob/Queue/Table Service Stats Fails

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#209]
```Python
from azure.storage.queue import QueueService
cs = "blah"
client = QueueService(connection_string=cs)
client.get_queue_service_stats()
```

This yields the following:
```
Traceback (most recent call last):
  File "C:\...\site-packages\requests\packages\urllib3\connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\...\site-packages\requests\packages\urllib3\util\connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "C:\...\Python\Python35-32\Lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "C:\...\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\...\site-packages\requests\packages\urllib3\connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "C:\...\site-packages\requests\packages\urllib3\connection.py", line 217, in connect
    conn = self._new_conn()
  File "C:\...\site-packages\requests\packages\urllib3\connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x034332F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

The calls to the TableService/BaseBlobService do the same thing. There is a call in the FileService `get_share_stats` which does work, but it is specific to a share, and not the service. I couldn't find a service stats call for the FileService.

**Comment by pemari-msft** [comment]
Service Stats only applies to the secondary. Are you using an RA-GRS enabled account? What is the format of your connection string?

**Comment by tjprescott** [comment]
Ah, okay, that was the issue. I created a Standard_RAGRS account and they worked fine. It would be more helpful if it responded with an error message to that effect instead of the repeated HTTPS connection failure messages.
