### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-storage-python#241]
This error appeared in the past and now it is a real issue. I'm trying to use azure-storage module with Python 3.4 (3.4.3 on fresh Ubuntu 14.04 VM in Azure or 3.4.4 on Mac OS X) and it is not possible at all.

Ubuntu 14.04:

`michal@backtest:~$ python3 run.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/storageclient.py", line 206, in _perform_request
    self.authentication.sign_request(request)
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/_auth.py", line 97, in sign_request
    self._add_authorization_header(request, string_to_sign)
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/_auth.py", line 51, in _add_authorization_header
    signature = _sign_string(self.account_key, string_to_sign)
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/_common_conversion.py", line 88, in _sign_string
    key = _decode_base64_to_bytes(key)
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/_common_conversion.py", line 78, in _decode_base64_to_bytes
    return base64.b64decode(data)
  File "/usr/lib/python3.4/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding`

Mac OS X:

`/Users/michal/dev/tablebackup/virtualenv/bin/python /Users/michal/dev/tablebackup/run.py
Traceback (most recent call last):
  File "/Users/michal/dev/tablebackup/virtualenv/lib/python3.4/site-packages/azure/storage/storageclient.py", line 206, in _perform_request
    self.authentication.sign_request(request)
  File "/Users/michal/dev/tablebackup/virtualenv/lib/python3.4/site-packages/azure/storage/_auth.py", line 97, in sign_request
    self._add_authorization_header(request, string_to_sign)
  File "/Users/michal/dev/tablebackup/virtualenv/lib/python3.4/site-packages/azure/storage/_auth.py", line 51, in _add_authorization_header
    signature = _sign_string(self.account_key, string_to_sign)
  File "/Users/michal/dev/tablebackup/virtualenv/lib/python3.4/site-packages/azure/storage/_common_conversion.py", line 88, in _sign_string
    key = _decode_base64_to_bytes(key)
  File "/Users/michal/dev/tablebackup/virtualenv/lib/python3.4/site-packages/azure/storage/_common_conversion.py", line 78, in _decode_base64_to_bytes
    return base64.b64decode(data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding`

**Comment by smereczynski** [comment]
The same situation in docker with Python 3.5.2. In all cases there is azure-storage 0.33.0.

<img width="1280" alt="docker" src="https://cloud.githubusercontent.com/assets/705653/21315760/f59739c4-c5fd-11e6-8a81-f748ed0c97da.png">

**Comment by rambo-msft** [comment]
@smereczynski 
Looking at the code, it appears you're passing in the values `'myaccount'`, and `'mykey'` directly instead of using the variables you populated.
If that is not the case, make sure you the `account_key` you're providing is as-is from the Azure portal or wherever you received your key.

**Comment by rambo-msft** [comment]
Otherwise, take a look at the resolution for the same error on #31 and #159.
If you're still having issues, report back and we can investigate further.

**Comment by smereczynski** [comment]
@rambo-msft and you are totally right. Now look at the documentation:

<img width="749" alt="zrzut ekranu 2016-12-19 o 16 47 28" src="https://cloud.githubusercontent.com/assets/705653/21318809/091c6930-c60b-11e6-81dc-8e8e0b098329.png">

**Comment by smereczynski** [comment]
Above sample is from docs.microsoft.com. It needs to be fixed.

**Comment by rambo-msft** [comment]
@smereczynski ,
While it would be nice to assume that our users understand these values are placeholders, we also explicitly state below:
> The following code creates a TableService object by using the storage account name and account key. **Replace 'myaccount' and 'mykey'** with your account name and key.

**Comment by smereczynski** [comment]
It is buggy documentation. If You want to use some "placeholder" in Python, don't use ' '. Because if You copy-paste this code, it will not work and You cannot find out fast what is happening. If there was <myaccount> it is CLEAR thet it is placeholder.

**Comment by squillace** [comment]
@smereczynski thanks for noting this. Follow up in email, but we'll find the right solution. @boumenot
