### ISSUE TITLE
Failed to deploy as Web App on Azure: "Unable to find vcvarsall.bat" in cffi

### ISSUE THREAD

**Issue by vejuhust** [Azure/azure-storage-python#247]
Here's my `requirements.txt`:
~~~txt
azure-common==1.1.4
azure-nspkg==1.0.0
azure-storage==0.33.0
BaseHash==3.0.4
cffi==1.9.1
click==6.7
cryptography==1.7.1
Flask==0.12
Flask-Script==2.0.5
Flask-SQLAlchemy==2.1
idna==2.2
itsdangerous==0.24
Jinja2==2.9.4
MarkupSafe==0.23
pyasn1==0.1.9
pycparser==2.17
pyodbc==4.0.0
python-dateutil==2.6.0
requests==2.12.4
six==1.10.0
SQLAlchemy==1.1.4
Werkzeug==0.11.15
~~~

My error log attached below:

```log
remote: Detecting Python runtime from runtime.txt
remote: Detected python-3.4
remote: Creating python-3.4 virtual environment.
remote: .................................
remote: Pip install requirements.
remote: Downloading/unpacking azure-common==1.1.4 (from -r requirements.txt (line 1))
remote:   Downloading azure_common-1.1.4-py2.py3-none-any.whl
remote: Downloading/unpacking azure-nspkg==1.0.0 (from -r requirements.txt (line 2))
remote:   Downloading azure_nspkg-1.0.0-py2.py3-none-any.whl
remote: Downloading/unpacking azure-storage==0.33.0 (from -r requirements.txt (line 3))
remote: Downloading/unpacking BaseHash==3.0.4 (from -r requirements.txt (line 4))
remote:   Downloading BaseHash-3.0.4.zip
remote:   Running setup.py (path:D:\home\site\wwwroot\env\build\BaseHash\setup.py) egg_info for package BaseHash
remote:     
remote: Downloading/unpacking cffi==1.9.1 (from -r requirements.txt (line 5))
remote:   Running setup.py (path:D:\home\site\wwwroot\env\build\cffi\setup.py) egg_info for package cffi
remote:     Traceback (most recent call last):
remote:       File "<string>", line 17, in <module>
remote:       File "D:\home\site\wwwroot\env\build\cffi\setup.py", line 98, in <module>
remote:         if sys.platform == 'win32' and uses_msvc():
remote:       File "D:\home\site\wwwroot\env\build\cffi\setup.py", line 76, in uses_msvc
remote:         return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
remote:       File "D:\python34\lib\distutils\command\config.py", line 227, in try_compile
remote:         self._compile(body, headers, include_dirs, lang)
remote:       File "D:\python34\lib\distutils\command\config.py", line 133, in _compile
remote:         self.compiler.compile([src], include_dirs=include_dirs)
remote:       File "D:\python34\lib\distutils\msvc9compiler.py", line 460, in compile
remote:         self.initialize()
remote:       File "D:\python34\lib\distutils\msvc9compiler.py", line 371, in initialize
remote:         vc_env = query_vcvarsall(VERSION, plat_spec)
remote:       File "D:\python34\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall
remote:         raise DistutilsPlatformError("Unable to find vcvarsall.bat")
remote:     distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
remote:     Complete output from command python setup.py egg_info:
remote:     Traceback (most recent call last):
remote: 
remote:   File "<string>", line 17, in <module>
remote: 
remote:   File "D:\home\site\wwwroot\env\build\cffi\setup.py", line 98, in <module>
remote: 
remote:     if sys.platform == 'win32' and uses_msvc():
remote: 
remote:   File "D:\home\site\wwwroot\env\build\cffi\setup.py", line 76, in uses_msvc
remote: 
remote:     return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
remote: 
remote:   File "D:\python34\lib\distutils\command\config.py", line 227, in try_compile
remote: 
remote:     self._compile(body, headers, include_dirs, lang)
remote: 
remote:   File "D:\python34\lib\distutils\command\config.py", line 133, in _compile
remote: 
remote:     self.compiler.compile([src], include_dirs=include_dirs)
remote: 
remote:   File "D:\python34\lib\distutils\msvc9compiler.py", line 460, in compile
remote: 
remote:     self.initialize()
remote: 
remote:   File "D:\python34\lib\distutils\msvc9compiler.py", line 371, in initialize
remote: 
remote:     vc_env = query_vcvarsall(VERSION, plat_spec)
remote: 
remote:   File "D:\python34\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall
remote: 
remote:     raise DistutilsPlatformError("Unable to find vcvarsall.bat")
remote: 
remote: distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
remote: 
remote: ----------------------------------------
remote: Cleaning up...
remote: Command python setup.py egg_info failed with error code 1 in D:\home\site\wwwroot\env\build\cffi
remote: Storing debug log for failure in D:\home\pip\pip.log
remote: An error has occurred during web site deployment.
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.
```

**Comment by vejuhust** [comment]
Dependencies: `cffi`<-`cryptography`<-`azure-storage`

**Comment by rambo-msft** [comment]
Hi @vejuhust , please see #219 for resolution.

Thanks!
