### ISSUE TITLE
What is the return format of get_container_metadata?

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-storage-python#252]
I tried testing it myself but I got an error:

```
>>> import azure.storage.blob.baseblobservice
>>> a = azure.storage.blob.baseblobservice.BaseBlobService(account_name="name", account_key="key+as+a+string==")
>>> a.get_container_metadata("name1")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/azure/storage/blob/baseblobservice.py", line 654, in get_container_metadata
    return self._perform_request(request, _parse_metadata)
  File "/Library/Python/2.7/site-packages/azure/storage/storageclient.py", line 266, in _perform_request
    raise ex
azure.common.AzureException: AttributeError: 'X509' object has no attribute '_x509'
```

**Comment by rambo-msft** [comment]
Hi @zfrenchee ,
Take a look [here](https://github.com/Azure/azure-storage-python/blob/717f616809c82b6cbf3e258f3d94303e6fabe411/samples/blob/container_usage.py#L96-L118)

As for the error, could you update your `cryptography` and `requests` packages if not already.
Historically, these type of issues are caused by an out of date pyOpenSSL.
