### ISSUE TITLE
ImportError: No module named storage.blob

### ISSUE THREAD

**Issue by sandeepvaidya** [Azure/azure-storage-python#295]
I am getting the same error as in Issue #262:
ImportError: No module named storage.blob #262
#262

I am in fact trying to run the same code:

from azure.storage.blob import BlockBlobService
block_blob_service = BlockBlobService(account_name='myaccount', account_key='mykey')
block_blob_service.create_container('backups')

Error:
$ python azure_github.py
Traceback (most recent call last):
File "azure_github.py", line 1, in
from azure.storage.blob import BlockBlobService
File "/xxx/yyyyy/azure.py", line 1, in
from azure.storage.blob import PageBlobService
ImportError: No module named storage.blob

1) I am working on a 64 bit RHEL server:
$ python -c 'import sys,platform; print platform.architecture()[0], sys.maxsize > 2**32'
64bit True
$ python -c 'import struct;print( 8 * struct.calcsize("P"))'
64

2) I have installed python 2.7 (64bits)
python -v
$ python -v | grep site-packages
installing zipimport hook

import zipimport # builtin
installed zipimport hook
/usr/lib64/python2.7/site.pyc matches /usr/lib64/python2.7/site.py

import site # precompiled from /usr/lib64/python2.7/site.pyc
/usr/lib64/python2.7/os.pyc matches /usr/lib64/python2.7/os.py

import os # precompiled from /usr/lib64/python2.7/os.pyc

...
..

3) I have 2 site-packages directories:

./usr/lib/python2.7/site-packages
./usr/lib64/python2.7/site-packages

and when I install the azure-storage package, it gets installed in the
/usr/lib/python2.7/site-packages directory.

$ sudo pip install azure-storage
Collecting azure-storage
Downloading azure_storage-0.34.2-py2.py3-none-any.whl (187kB)
100% |████████████████████████████████| 194kB 1.6MB/s
Requirement already satisfied: cryptography in /usr/lib64/python2.7/site-packages (from azure-storage)
Collecting azure-nspkg>=2.0.0 (from azure-storage)
Using cached azure_nspkg-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from azure-storage)
Collecting azure-common>=1.1.5 (from azure-storage)
Using cached azure_common-1.1.5-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from azure-storage)
Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography->azure-storage)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python2.7/site-packages (from setuptools>=11.3->cryptography->azure-storage)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography->azure-storage)
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging->cryptography->azure-storage)
Installing collected packages: azure-nspkg, azure-common, azure-storage
Successfully installed azure-common-1.1.5 azure-nspkg-2.0.0 azure-storage-0.34.2

4) In directoy, /usr/lib/python2.7/site-packages
azure
azure_common-1.1.5.dist-info
azurelinuxagent
azure_nspkg-2.0.0.dist-info
azure_storage-0.34.2.dist-info

In directoy, /usr/lib64/python2.7/site-packages there are no azure packages.

Shouldn't the azure packages install in lib64 ? Is this causing the ImportError ?

**Comment by sandeepvaidya** [comment]
I will close this issue as I now think the problem was that i had a file named azure.py in the same directory. 
It did not like the azure filename!
