### ISSUE TITLE
Please pin the `crytopgraphy` to a specific a version number 

### ISSUE THREAD

**Issue by bugra** [Azure/azure-storage-python#367]
Today, Python package [`crytopgraphy`](https://pypi.python.org/pypi/cryptography) released a new build and this is breaking all of the installs `azure-storage-blob` through `pip` as this package is not pinned to a specific version number.

```
10:51:05 Collecting azure-storage-nspkg>=2.0.0 (from azure-storage-blob==0.37.0->-r /root/python/recommender/product_similarity/requirements.txt (line 19))
10:51:05   Downloading azure_storage_nspkg-2.0.0-py2.py3-none-any.whl
10:51:05 Collecting cryptography (from azure-storage-blob==0.37.0->-r /root/python/recommender/product_similarity/requirements.txt (line 19))
10:51:05   Downloading cryptography-2.1-cp35-cp35m-manylinux1_x86_64.whl (2.2MB)
10:51:06 Exception:
10:51:06 Traceback (most recent call last):
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2711, in _dep_map
10:51:06     return self.__dep_map
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2545, in __getattr__
10:51:06     raise AttributeError(attr)
10:51:06 AttributeError: _DistInfoDistribution__dep_map
10:51:06 During handling of the above exception, another exception occurred:
10:51:06 Traceback (most recent call last):
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
10:51:06     req = REQUIREMENT.parseString(requirement_string)
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 1137, in parseString
10:51:06     raise exc
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 1127, in parseString
10:51:06     loc, tokens = self._parse( instring, 0 )
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 1001, in _parseNoCache
10:51:06     loc,tokens = self.parseImpl( instring, preloc, doActions )
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 2412, in parseImpl
10:51:06     loc, exprtokens = e._parse( instring, loc, doActions )
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 1005, in _parseNoCache
10:51:06     loc,tokens = self.parseImpl( instring, preloc, doActions )
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/pyparsing.py", line 2215, in parseImpl
10:51:06     raise ParseException(instring, loc, self.errmsg, self)
10:51:06 pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 12), (line:1, col:13)
10:51:06 During handling of the above exception, another exception occurred:
10:51:06 Traceback (most recent call last):
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2788, in __init__
10:51:06     super(Requirement, self).__init__(requirement_string)
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
10:51:06     requirement_string[e.loc:e.loc + 8]))
10:51:06 pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'; python'"
10:51:06 During handling of the above exception, another exception occurred:
10:51:06 Traceback (most recent call last):
10:51:06   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
10:51:06     status = self.run(options, args)
10:51:06   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 328, in run
10:51:06     wb.build(autobuilding=True)
10:51:06   File "/usr/lib/python3/dist-packages/pip/wheel.py", line 748, in build
10:51:06     self.requirement_set.prepare_files(self.finder)
10:51:06   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
10:51:06     ignore_dependencies=self.ignore_dependencies))
10:51:06   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 647, in _prepare_file
10:51:06     set(req_to_install.extras) - set(dist.extras)
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2670, in extras
10:51:06     return [dep for dep in self._dep_map if dep]
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2713, in _dep_map
10:51:06     self.__dep_map = self._compute_dependencies()
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2723, in _compute_dependencies
10:51:06     reqs.extend(parse_requirements(req))
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2781, in parse_requirements
10:51:06     yield Requirement(line)
10:51:06   File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2790, in __init__
10:51:06     raise RequirementParseError(str(e))
10:51:06 pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; python'"
````

**Comment by bugra** [comment]
Please, consider doing the same thing for all other third party dependencies: https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/setup.py#L86-L88

**Comment by lmazuel** [comment]
I'm not able to reproduce your issue with pip 9.0.1:
https://travis-ci.org/Azure/azure-storage-python/jobs/283836828

Usually this kind of requirement parsing issues are caused by an old version of pip. My current guess is that the cryptography team changed a little their setup,py, and that some metadata in the wheel file now requires more recent version of pip (we already got this with `requests` once). This has nothing to do with the storage package, and I don't recommend pinning the package version to support old version of pip.

Could you update your pip and tell us if this fixes your problem?

**Comment by zezha-msft** [comment]
@bugra Could you please update your pip and try again? I also cannot reproduce this issue.

@lmazuel thanks for the insights!

**Comment by bugra** [comment]
@zezha-msft @lmazuel Thanks for the explanation, but what is the correct version of pip I should be using?

**Comment by lmazuel** [comment]
@bugra See the ChangeLog of cryptography 2.1:
https://cryptography.io/en/latest/changelog/#v2-1
```
Installing cryptography now requires pip 6 or newer.
```

but the day after they released a 2.1.1 saying:
```
Fixed support for install with the system pip on Ubuntu 16.04.
```

My guess is that they require 8.1.2, even if this were not on purpose (hence the patch 2.1.1).

See for reference this `requests` issue, where it seems that 8.1.2 has some drastic change compared to 8.1.1 (for a bug fix version that's bad, but anyway...)
https://github.com/requests/requests/issues/4006

**Comment by bugra** [comment]
@lmazuel Okay, thanks for this update and I am perfectly clear that it is related to `crytography` change regarding to the `pip`. 

However, I am still not clear why you do not want to pin the third party packages in this python package. Currently, whenever a change happens to the third party packages; this is going to break the build. I still would like to the `azure-storage-python` to pin third party packages so that we can have deterministic, repeatable builds when we have a dependency on it.

**Comment by lmazuel** [comment]
This is not the recommendation in Python, this is the role of the requirements.txt file. There is plenty of articles, but this one is the most popular (by Donald Stufft, creator of pip):
https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by bugra** [comment]
Okay, thanks for the explanation.
