### ISSUE TITLE
MD5 validation using Storage SDK is not happening while databricks filesystem API reports MD5 mismatch

### ISSUE THREAD

**Issue by pchinta** [Azure/azure-storage-python#627]
### Which service(blob, file, queue) does this issue concern?
Blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-blob 2.1.0

### Have you found a mitigation/solution?
No

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @pchinta, thanks for reaching out.

Could you please provide a bit more details so that we can try to repro this issue? How big was the file? Have you validated the stored MD5 on your own?

**Comment by pchinta** [comment]
+ Blaize

Hi,

The blob is stored on a storage account owned by Blaize (copied on the thread). Blob size is 4MB and it is outlook mail. Since its PII info we do not have copy of the blob, and so did not validate MD5 of the blob. Attached is the error reported for the blob in scope of the issue by databricks file system API for the same file.

Caused by: com.microsoft.azure.storage.StorageException: Blob data corrupted (integrity check failed), Expected value is c1b80a33c85d2b1cb092d92fc817324d, retrieved wbgKM8hdKxywktkvyBcyTQ==
               at com.microsoft.azure.storage.blob.BlobInputStream.readInternal(BlobInputStream.java:466)
               at com.microsoft.azure.storage.blob.BlobInputStream.read(BlobInputStream.java:420)
               at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
               at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
               at java.io.DataInputStream.read(DataInputStream.java:149)


@Blaize Berry <Blaize.Berry@walmart.com><mailto:Blaize.Berry@walmart.com>, Could you please help us understand on MD5 computation to setup repro by Azure Storage SDK team?


Best Regards,
Purna Chandra Rao Chinta
Support Escalation Engineer
Microsoft Azure Rapid Response Team
Email : pchinta@microsoft.com<mailto:pchinta@microsoft.com>
Working hours: 0900 – 2000 Central Time (Wed – Sat)
If you need immediate attention for any of the ongoing case while I am out of shift, please send a separate email with case ID to arrbackup@microsoft.com<mailto:arrbackup@microsoft.com>. A Duty Manager will take action and loop in an available ARR engineer to help you.  If you have any feedback of your Support Experience, please feel free to contact my manager – Kirk Beller at kbeller@microsoft.com<mailto:kbeller@microsoft.com>, or +1 (701) 2816543.
[Microsoft Logo]

**Comment by pchinta** [comment]
We are not explicitly computing the MD5 of the blob. I believe that functionality is provided out of the box via the Python SDK when the validate_content flag is set to True. I believe that there is some subtlety to the computation in that an MD5 is only evaluated for the first 4 MB with that flag set to true for performance purposes (see https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/baseblobservice.py#L1923
), but the particular blob that we’re encountering hash mismatch errors with in Databricks mounted storage is less than 1 MB in size so this shouldn’t be a factor. I can’t comment with 100% certainty on how Databricks computes the MD5 with their mounted storage setup, but from the logs I’ve seen it looks like they’re using the Java SDK for Azure Storage under the hood.

Best,
Blaize Berry
Staff Software Engineer (Machine Learning) – Austin, TX
M: 314-578-0629
Blaize.Berry@Walmart.com<mailto:Jason.Norris@Walmart.com>
[/Users/b0b00ci/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_301523036]


From: Purna Chandra Rao Chinta <pchinta@microsoft.com>
Date: Wednesday, August 14, 2019 at 6:00 PM
To: Azure/azure-storage-python <reply@reply.github.com>, Azure/azure-storage-python <azure-storage-python@noreply.github.com>, Blaize Berry <Blaize.Berry@walmart.com>
Cc: Mention <mention@noreply.github.com>, Microsoft - Alex Kaps <Alexander.Kaps@microsoft.com>
Subject: EXT: RE: [Azure/azure-storage-python] MD5 validation using Storage SDK is not happening while databricks filesystem API reports MD5 mismatch (#627)

+ Blaize

Hi,

The blob is stored on a storage account owned by Blaize (copied on the thread). Blob size is 4MB and it is outlook mail. Since its PII info we do not have copy of the blob, and so did not validate MD5 of the blob. Attached is the error reported for the blob in scope of the issue by databricks file system API for the same file.

Caused by: com.microsoft.azure.storage.StorageException: Blob data corrupted (integrity check failed), Expected value is c1b80a33c85d2b1cb092d92fc817324d, retrieved wbgKM8hdKxywktkvyBcyTQ==
               at com.microsoft.azure.storage.blob.BlobInputStream.readInternal(BlobInputStream.java:466)
               at com.microsoft.azure.storage.blob.BlobInputStream.read(BlobInputStream.java:420)
               at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
               at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
               at java.io.DataInputStream.read(DataInputStream.java:149)


@Blaize Berry <Blaize.Berry@walmart.com><mailto:Blaize.Berry@walmart.com>, Could you please help us understand on MD5 computation to setup repro by Azure Storage SDK team?


Best Regards,
Purna Chandra Rao Chinta
Support Escalation Engineer
Microsoft Azure Rapid Response Team
Email : pchinta@microsoft.com<mailto:pchinta@microsoft.com>
Working hours: 0900 – 2000 Central Time (Wed – Sat)
If you need immediate attention for any of the ongoing case while I am out of shift, please send a separate email with case ID to arrbackup@microsoft.com<mailto:arrbackup@microsoft.com>. A Duty Manager will take action and loop in an available ARR engineer to help you.  If you have any feedback of your Support Experience, please feel free to contact my manager – Kirk Beller at kbeller@microsoft.com<mailto:kbeller@microsoft.com>, or +1 (701) 2816543.
[Microsoft Logo]

**Comment by pchinta** [comment]
Hi,

We can compute MD5 of the blob in storage account and see if MD5 being updated on blob is correct..

https://github.com/giventocode/azure-blob-md5

For windows:

  1.  Install GO (as on link).
  2.  Create a folder for md5 and open cmdprompt (as admin), browse to the folder and run below commands:

go get github.com/giventocode/azure-blob-md5

go build -o bmd5.exe github.com/giventocode/azure-blob-md5

  1.  Create environment variables as ACCOUNT_NAME and ACCOUNT_KEY and provide values inline to storage account in scope of issue.
  2.  Open another prompt (as admin) as environment variables created above will not be available at cmd prompt at step 2 above.
  3.  Browse to “bmd5.exe” (at path on step 2) and run below command:

bmd5 -b blob -c container

  1.  Validate the MD5 generated with

  1.  MD5 reported on error (one of them)
  2.  MD5 on blob (content-md5 on azure portal).
If both match, then there is issue with md5 computed by databricks file system API.


Best Regards,
Purna Chandra Rao Chinta

**Comment by pchinta** [comment]
Hi Purna,

I have computed the MD5 of the blob in the storage account and got c1b80a33c85d2b1cb092d92fc817324d, which is consistent with the ContentMD5 blob property.

Best,
Blaize Berry
Staff Software Engineer (Machine Learning) – Austin, TX
M: 314-578-0629
Blaize.Berry@Walmart.com<mailto:Jason.Norris@Walmart.com>
[/Users/b0b00ci/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_301523036]


From: Purna Chandra Rao Chinta <pchinta@microsoft.com>
Date: Thursday, August 15, 2019 at 7:25 AM
To: Blaize Berry <Blaize.Berry@walmart.com>, Azure/azure-storage-python <reply@reply.github.com>, Azure/azure-storage-python <azure-storage-python@noreply.github.com>
Cc: Mention <mention@noreply.github.com>, Microsoft - Alex Kaps <Alexander.Kaps@microsoft.com>
Subject: EXT: RE: [Azure/azure-storage-python] MD5 validation using Storage SDK is not happening while databricks filesystem API reports MD5 mismatch (#627)

Hi,

We can compute MD5 of the blob in storage account and see if MD5 being updated on blob is correct..

https://github.com/giventocode/azure-blob-md5

For windows:

  1.  Install GO (as on link).
  2.  Create a folder for md5 and open cmdprompt (as admin), browse to the folder and run below commands:

go get github.com/giventocode/azure-blob-md5

go build -o bmd5.exe github.com/giventocode/azure-blob-md5

  1.  Create environment variables as ACCOUNT_NAME and ACCOUNT_KEY and provide values inline to storage account in scope of issue.
  2.  Open another prompt (as admin) as environment variables created above will not be available at cmd prompt at step 2 above.
  3.  Browse to “bmd5.exe” (at path on step 2) and run below command:

bmd5 -b blob -c container

  1.  Validate the MD5 generated with

  1.  MD5 reported on error (one of them)
  2.  MD5 on blob (content-md5 on azure portal).
If both match, then there is issue with md5 computed by databricks file system API.


Best Regards,
Purna Chandra Rao Chinta

**Comment by pchinta** [comment]
Also, when I try to retrieve the blob with the Databricks fs utilities I get the error below. Please note the checksum values that I’ve bolded in the stack trace. As you said, it appears that the Databricks FSUtils is computing the checksum incorrectly:

ExecutionError: An error occurred while calling z:com.databricks.backend.daemon.dbutils.FSUtils.head.
: java.io.IOException
                at com.microsoft.azure.storage.core.Utility.initIOException(Utility.java:737)
                at com.microsoft.azure.storage.blob.BlobInputStream.readInternal(BlobInputStream.java:466)
                at com.microsoft.azure.storage.blob.BlobInputStream.read(BlobInputStream.java:420)
                at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
                at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
                at java.io.DataInputStream.read(DataInputStream.java:149)
                at shaded.databricks.org.apache.hadoop.fs.azure.NativeAzureFileSystem$NativeAzureFsInputStream.read(NativeAzureFileSystem.java:855)
                at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
                at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
                at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
                at java.io.DataInputStream.readFully(DataInputStream.java:195)
                at java.io.DataInputStream.readFully(DataInputStream.java:169)
                at com.databricks.backend.daemon.dbutils.FSUtils$$anonfun$head$1.apply(DBUtilsCore.scala:200)
                at com.databricks.backend.daemon.dbutils.FSUtils$$anonfun$head$1.apply(DBUtilsCore.scala:190)
                at com.databricks.backend.daemon.dbutils.FSUtils$.com$databricks$backend$daemon$dbutils$FSUtils$$withFsSafetyCheck(DBUtilsCore.scala:81)
                at com.databricks.backend.daemon.dbutils.FSUtils$.head(DBUtilsCore.scala:190)
                at com.databricks.backend.daemon.dbutils.FSUtils.head(DBUtilsCore.scala)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
                at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
                at py4j.Gateway.invoke(Gateway.java:295)
                at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
                at py4j.commands.CallCommand.execute(CallCommand.java:79)
                at py4j.GatewayConnection.run(GatewayConnection.java:251)
                at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.storage.StorageException: Blob data corrupted (integrity check failed), Expected value is c1b80a33c85d2b1cb092d92fc817324d, retrieved wbgKM8hdKxywktkvyBcyTQ==
                ... 27 more

Best,
Blaize Berry
Staff Software Engineer (Machine Learning) – Austin, TX
M: 314-578-0629
Blaize.Berry@Walmart.com<mailto:Jason.Norris@Walmart.com>
[/Users/b0b00ci/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_301523036]


From: Blaize Berry <Blaize.Berry@walmart.com>
Date: Thursday, August 15, 2019 at 9:35 AM
To: Purna Chandra Rao Chinta <pchinta@microsoft.com>, Azure/azure-storage-python <reply@reply.github.com>, Azure/azure-storage-python <azure-storage-python@noreply.github.com>
Cc: Mention <mention@noreply.github.com>, Microsoft - Alex Kaps <Alexander.Kaps@microsoft.com>
Subject: Re: [Azure/azure-storage-python] MD5 validation using Storage SDK is not happening while databricks filesystem API reports MD5 mismatch (#627)

Hi Purna,

I have computed the MD5 of the blob in the storage account and got c1b80a33c85d2b1cb092d92fc817324d, which is consistent with the ContentMD5 blob property.

Best,
Blaize Berry
Staff Software Engineer (Machine Learning) – Austin, TX
M: 314-578-0629
Blaize.Berry@Walmart.com<mailto:Jason.Norris@Walmart.com>
[/Users/b0b00ci/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_301523036]


From: Purna Chandra Rao Chinta <pchinta@microsoft.com>
Date: Thursday, August 15, 2019 at 7:25 AM
To: Blaize Berry <Blaize.Berry@walmart.com>, Azure/azure-storage-python <reply@reply.github.com>, Azure/azure-storage-python <azure-storage-python@noreply.github.com>
Cc: Mention <mention@noreply.github.com>, Microsoft - Alex Kaps <Alexander.Kaps@microsoft.com>
Subject: EXT: RE: [Azure/azure-storage-python] MD5 validation using Storage SDK is not happening while databricks filesystem API reports MD5 mismatch (#627)

Hi,

We can compute MD5 of the blob in storage account and see if MD5 being updated on blob is correct..

https://github.com/giventocode/azure-blob-md5

For windows:

  1.  Install GO (as on link).
  2.  Create a folder for md5 and open cmdprompt (as admin), browse to the folder and run below commands:

go get github.com/giventocode/azure-blob-md5

go build -o bmd5.exe github.com/giventocode/azure-blob-md5

  1.  Create environment variables as ACCOUNT_NAME and ACCOUNT_KEY and provide values inline to storage account in scope of issue.
  2.  Open another prompt (as admin) as environment variables created above will not be available at cmd prompt at step 2 above.
  3.  Browse to “bmd5.exe” (at path on step 2) and run below command:

bmd5 -b blob -c container

  1.  Validate the MD5 generated with

  1.  MD5 reported on error (one of them)
  2.  MD5 on blob (content-md5 on azure portal).
If both match, then there is issue with md5 computed by databricks file system API.


Best Regards,
Purna Chandra Rao Chinta

**Comment by pchinta** [comment]
Hi Blaize,

As we understood from the call, content-MD5 is being computed manually by your application and is the reason we were seeing different MD5 value.

As agreed we will close this thread. Thank you for your help.


Best Regards,
Purna Chandra Rao Chinta

**Comment by zezha-msft** [comment]
@pchinta I see the issue was resolved. 

To clarify, `validate_content` verifies the individual chunks when downloading a large blob.

On a side note, please avoid exposing cx's contact information on Github.
